### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Hanh668**

### CODE REVIEW

**Comment by philschmid** [comment]
What's your intention behind adding a `SECURITY.md`?

**Comment by Cerchie** [comment]
Hello world ! :wave:

**Comment by Cerchie** [comment]
Hello world ! :wave:

**Comment by Cerchie** [comment]
Hello! :wave:

**Comment by Cerchie** [comment]
Hello! :wave:  github.event.pull_request.user.login

**Pull request closed without merging**
